### ISSUE TITLE
usepackage无法载入问题

### ISSUE THREAD

**Issue by awakeljw** [alick/thulib-latex-talk#1]
wrong：l.46 \usepackage {listingsutf8}
 Package minted Error: You must invoke LaTeX with the -shell-escape flag.
需要载入包或者其它的操作嘛？

**Comment by alick** [comment]
用的什么 TeX 发行版哪个版本？

我印象中 TeX Live 最近版本都默认启用了部分 -shell-escape 功能

**Comment by donghaoye** [comment]
latex -version
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/W32TeX)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.21; using libpng 1.6.21
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04

**Comment by donghaoye** [comment]
这条命令可以设置好：tlmgr conf texmf shell_escape 0
或者这样运行 xelatex -shell-escape input_file

**Comment by alick** [comment]
@donghaoye 所以问题解决了对吧？

**Comment by alick** [comment]
Seems user conf issue
